#!/usr/bin/env bash
export JCO_ASHOST=13.76.229.211
export JCO_SYSNR=00
export JCO_CLIENT=001
export JCO_USER=
export JCO_PASSWD=
export JCO_LANG=en
export DESTINATION=
export JCO_GROUP=
export JCO_R3NAME=